### ISSUE TITLE
How to remove the about -> endpoint?

### ISSUE THREAD

**Issue by ozbillwang** [digitalcraftsman/hugo-agency-theme#100]
The icon defined in about ->endpoint works fine on desktop, but when view with my mobile, the icon doesn't stay at middle. 

So how to always keep it in middle, or how to remove it from `about` I comments the line of endpoint, but no help.

```diff
    # About section
  [params.about]
    enable = true
    title = "About"
    subtitle = "Lorem ipsum dolor sit amet consectetur."
+    endpoint = "Be part<br>of our<br>story!"
```

**Comment by lunk-liu** [comment]
Remove from template /layouts/partials/about.html :
https://github.com/digitalcraftsman/hugo-agency-theme/blob/master/layouts/partials/about.html#L32
```
<li class="timeline-inverted">
            <div class="timeline-image">
              <h4>{{ with .Site.Params.about.endpoint }}{{ . | markdownify }}{{ end }}</h4>
            </div>
</li>
```
