### ISSUE TITLE
Extending theme with pages for other types of content

### ISSUE THREAD

**Issue by aahoogendoorn** [digitalcraftsman/hugo-agency-theme#101]
Hi guys, love the theme as is, but I would really like to extend it with pages for other types of content, such as posts, projects etc. Are you perhaps working on that? Otherwise, I'll create my own extensions to the theme.

**Comment by stp-ip** [comment]
We are currently in the process of adding more features. First iteration is a successor theme available here: github.com/okkur/syna. It's still a work in progress, but each version should be stable in itself.

After this iteration is finished, I'll do my best to backport some features such as single pages, multilingual etc.

**Comment by stp-ip** [comment]
As hugo-agency-theme is mostly in maintenance mode and no new features will be added.
We created [Syna](https://syna.okkur.org) as a more flexible iteration of this theme.

Syna already has a lot more features and can easily be extended.
