### ISSUE TITLE
A bug of the path name.

### ISSUE THREAD

**Issue by doreentseng** [digitalcraftsman/hugo-agency-theme#105]
I downloaded the theme and followed the guide but it always showed
"GET http://localhost:1313/js/jquery-v3.3.1/jquery.min.js net::ERR_ABORTED"

Then I fixed it in /layouts/partials/js.html
Change 
`<script src="{{ "js/jquery-v3.3.1/jquery.min.js"| absURL }}"></script>`
to
`<script src="{{ "js/jquery-v3.1.1/jquery.min.js"| absURL }}"></script>`

Thanks~

**Comment by stp-ip** [comment]
Fixed with #106 or at least the problematic change was reverted. Sorry for the oversight. You can add a PR fixing the script tag and the folder name as in #104
