### ISSUE TITLE
Contact From Validation on Firefox

### ISSUE THREAD

**Issue by mcallari** [digitalcraftsman/hugo-agency-theme#108]
For me, the contact form doesn't pass validation in FF 57.0.1. Name, email, and text validates, but not the textarea, and the submit button never enables. Does anyone else have this issue?

**Comment by stp-ip** [comment]
Hey thanks for the report. What hosting service are you using? Do you merge JS resources into a single file?

**Comment by yatzy** [comment]
Same behaviour as mcallari with latest Chrome (63). For older Firefox (45) seems to get past the validation but error while pushing the submit button "Message could not be send. Please contact us at...". I'm hosting at Netlify.

**Comment by stp-ip** [comment]
@yatzy we'll backport the latest refactoring of the contact form with straight netlify support from github.com/okkur/syna this week or next. That should fix this issue and also make it easy to use the contact form straight with netlify without a separate service.

**Comment by yatzy** [comment]
Awesome to hear!

**Comment by stp-ip** [comment]
Should be fixed via #116 
This also adds recaptcha and netlify form support. Would be great, if you could test, if this solves your issues.
