### ISSUE TITLE
External url with hashbang /#/ or /#!/ won't open

### ISSUE THREAD

**Issue by Karadox** [digitalcraftsman/hugo-agency-theme#110]
The code to allow for smooth scrolling doesn't take into account urls with hashbangs.

To reproduce enter the following url in a link and click on it.
http://example.com/base/index.html/#!/a

Just the check if there is a hash is not enough.
I've added comparing against host on line 4 of agency.js (Not the best fix, i know, but works for external links)
`if (this.hash && window.location.pathname == "/" && window.location.host == this.host) {`

greetz

**Comment by stp-ip** [comment]
Closing for now. If this is still a bug, let us know.
