### ISSUE TITLE
Change icon in services section

### ISSUE THREAD

**Issue by carlosneftaly** [digitalcraftsman/hugo-agency-theme#111]
I'm really newbie using hugo. Im trying to set my web using the agency theme. I would ask you about how change the icons in the services section. I would like to use an  image or icon storage in my folder. 
Thanks in advance for you help!

**Comment by stp-ip** [comment]
They can be changed within the config.toml. They use icons from an icon set. https://github.com/digitalcraftsman/hugo-agency-theme/blob/master/exampleSite/config.toml#L92
So a custom one is not easily done, but usually there are enough to choose from.
It's using fontawesome v4: https://fontawesome.com/v4.7.0/
