### ISSUE TITLE
Contact form doesnt work

### ISSUE THREAD

**Issue by 11jwolfe2** [digitalcraftsman/hugo-agency-theme#112]
Get the error that the  server is currently down. 

Have edited the email and verified that the post function works in the chrome inspect console. I am having the same issue with the Clean-Blog theme as well using formspree.io. I am assuming it is a jquery issue, but I am a little to new to know the answer. I am hosting the site via a git hubrepo, feel free to visit the site at [theinternet.onthewifi.com](theinternet.onthewifi.com), the repo is [here](https://github.com/11jwolfe2/11jwolfe2.github.io)

![image](https://user-images.githubusercontent.com/15834012/36791204-215cfb20-1c65-11e8-8831-4755948d7c2a.png)

![image](https://user-images.githubusercontent.com/15834012/36791351-92a0d658-1c65-11e8-9c1f-d8c51072d4c4.png)

**Comment by 11jwolfe2** [comment]
I figured out the issue. It was with registering the website with freeform.io. I inserted their test form instead of the theme form and used that to send the initial email used to register the page. Then I changed the form back to the theme form and now the form is working. This is a weird issue with freeform.io, i believe.

**Comment by stp-ip** [comment]
Great to hear that was fixed \o/
