### ISSUE TITLE
contact form give a 400 js error

### ISSUE THREAD

**Issue by polya20** [digitalcraftsman/hugo-agency-theme#113]
jquery.min.js:4 POST http://formspree.io/hello@abundanceai.com 400 (BAD REQUEST)

**Comment by stp-ip** [comment]
Hard to debug, without more information. Any link to your site or code? Any additional info?

**Comment by polya20** [comment]
http://www.abundanceai.com/

**Comment by stp-ip** [comment]
As far as I can see you changed the agency.js code to not use json on the cross origin request, which leads to a cross origin error 405. The above error 400 (BAD REQUEST) didn't come up at all.

**Comment by polya20** [comment]
you are right michael. I was getting the 400 error yesterday night. I will try and fix the 405 error
