### ISSUE TITLE
Possible to have Portfolio scroll through images?

### ISSUE THREAD

**Issue by cnettles** [digitalcraftsman/hugo-agency-theme#115]
I apologize if this isn't the right place for this, I'm new to Hugo. 

I'm hoping to find a way that when I click on one of the previews in the Portfolio section, instead of just opening a single image I can scroll through a defined gallery of images.

For example, using the "Round Icons" to demonstrate. Say that icon developer had hundreds of icons to display vs. a few dozen, he/she may want to have several pages of icons a user could scroll through. That's what I'd like to achieve.

Hope that makes sense, I would love it if someone could point me in the right direction.

Thanks!

**Comment by stp-ip** [comment]
This is not supported in this theme. Also this will probably not be supported in the future. We won't change a lot in this theme, which adds new functionality. We will mostly backport fixes.
We are working on a new theme github.com/okkur/syna. It is currently work in progress and could have a few breaking changes still. You can open an issue there explaining your feature request and we might integrate it in a portfolio feature.

**Comment by cnettles** [comment]
Got it, I appreciate you taking the time to reply. I'll check out your new theme!
