### ISSUE TITLE
Team members don't appear on same line in Safari, but they render fine in Chrome/Firefox

### ISSUE THREAD

**Issue by kaleidoscopeINC** [digitalcraftsman/hugo-agency-theme#119]
The example has 3 team members. Two appear on the first line and the third member is moved to a second line. This happens in Safari.

In Chrome and Firefox, all 3 team members render on the same line. Is there a quick fix or workaround that I can add, perhaps some Safari specific code?

Here is the example page I was viewing with the browsers:
https://themes.gohugo.io/theme/agency/

**Comment by stp-ip** [comment]
Nothing that we know of yet. We'll look into the issue with Safari, but might take a bit.

**Comment by stp-ip** [comment]
@mpourismaiel ;)

**Comment by kaleidoscopeINC** [comment]
Thanks. I love the theme.

**Comment by stp-ip** [comment]
We are also working on https://github.com/okkur/syna as a more modular evolution, but it's not stable yet. Just wanted to give you a heads-up. Demo: https://syna-demo.okkur.io/

**Comment by kaleidoscopeINC** [comment]
Cool! I will take a look. Thank you!

**Comment by stp-ip** [comment]
As hugo-agency-theme is mostly in maintenance mode and no new features will be added.
We created [Syna](https://syna.okkur.org) as a more flexible iteration of this theme.

This should be fixed in Syna and it's corresponding [member fragment](https://about.okkur.org/syna/fragments/member)
