### ISSUE TITLE
Syna a flexible evolution of agency theme is ready

### ISSUE THREAD

**Issue by stp-ip** [digitalcraftsman/hugo-agency-theme#120]
# [Syna](https://github.com/okkur/syna)

Starting in 2017 we iterated on the agency theme.
With the amount of breaking changes, it was decided to create a new separate theme.
[Syna](https://github.com/okkur/syna) is based on the ideas behind the Agency Theme, but extends it to a much more customizable and cleaned up theme.

Check it out, test it and please provide feedback.

**Comment by stp-ip** [comment]
Thanks again to @digitalcraftsman and @davidtmiller for making it possible.

**Comment by digitalcraftsman** [comment]
Hello @stp-ip,

is my impression correct that your Syna theme reached a stable state in which it can act as a successor of the original Agency theme?

I'm thinking about ending the maintenance mode. If your theme can be seen as a stable successor I would redirect users to the Syna theme and archive this theme.

Independent of this decision I would like to thank you for all the work and support you've put into this theme. Chapeau!

**Comment by stp-ip** [comment]
Generally stable and used in production with 10+ sites now.

Recent Hugo version partially broke Syna, but haven't had time to pinpoint the issue. https://github.com/okkur/syna/issues/584

Thanks for your help.

**Comment by digitalcraftsman** [comment]
I've updated the status of this theme at the very top of the README. It informs the users that the development has been discontinued and the repository will be archived. The source code will of course still be accessible in its current state.

Dear all the best Michael.
