### ISSUE TITLE
Inability to customize Agency

### ISSUE THREAD

**Issue by forzoe** [digitalcraftsman/hugo-agency-theme#121]
So I would like to rename the tabs and reorder them, I have been able to rename them from Services, Portfolio, etc. The problem arrives when I try to reorder the tabs. Is there already a method of doing this?

**Comment by stp-ip** [comment]
Not sure, which tabs you are referring to. Could you provide a bit more detail?

**Comment by ebiwonjumit** [comment]
Im referring to the header tabs. I have tried to reorder them. That says Services, Portfolio, About, Team, Contact, External Link. I want to reorder them to About, Portfolio, Services, Team, Contact.

**Comment by mpourismaiel** [comment]
We don't plan on releasing any more features on the agency theme but you are welcome to create a PR. You can copy the `layouts/partials/nav.html` from the theme to your root directory in the same path and change the code, Hugo will override the partial. You can also take a look at [Syna](https://github.com/okkur/syna) which we are currently focused on. Syna offers a lot more flexibility, including reordering navigation links.

**Comment by stp-ip** [comment]
As hugo-agency-theme is mostly in maintenance mode and no new features will be added.
We created [Syna](https://syna.okkur.org) as a more flexible iteration of this theme.

Syna is highly customizable and enables you to even create your own fragments, while still maintaining the features of the other fragments. Take a look at the [documentation](https://about.okkur.org/syna/docs/fragments-implementation/)
