### ISSUE TITLE
demo page is down

### ISSUE THREAD

**Issue by eczajk1** [digitalcraftsman/hugo-agency-theme#122]
The demo page seems to be down: http://themes.gohugo.io/theme/agency/

<img width="413" alt="image" src="https://user-images.githubusercontent.com/2584923/45156276-b93b5f00-b1ab-11e8-9c2e-244e83859b61.png">

**Comment by stp-ip** [comment]
@digitalcraftsman anything that I can do?

**Comment by digitalcraftsman** [comment]
This is likely related to https://github.com/gohugoio/hugoThemes/issues/412. Currently, we're trying to isolate the issue with the build script. This theme isn't the only one that has a broken demo.

**Comment by eczajk1** [comment]
seems to be back up - probably has been for a while. Thanks!
