### ISSUE TITLE
How to add a blog page to Agency

### ISSUE THREAD

**Issue by coolhamid** [digitalcraftsman/hugo-agency-theme#123]
I just started with hugo agency theme and i really love it.  Just created my hugo website using the agency theme but confused on how add to add a blog page to it. Is there a way out? I will love  some posts from the blog page to be featured on the homepage? Can anybody help here? Thanks

**Comment by stp-ip** [comment]
Agency doesn't have a blog feature. From a feature perspective Agency won't get new features besides merging PRs. The focus is on [Syna Theme](github.com/okkur/syna), which is much more modular and flexible. It's getting more stable by the day and we would love people to check it out and iterate with us.

It has a blog feature and much more: https://syna-demo.okkur.io/dev/blog/
Sidenote: the blog feature is actuall using a so called "list" fragment: https://syna-demo.okkur.io/fragments/list/

**Comment by stp-ip** [comment]
As hugo-agency-theme is mostly in maintenance mode and no new features will be added.
We created [Syna](https://syna.okkur.org) as a more flexible iteration of this theme.

Syna can create a native blog integration (currently without an rss feed for now) with the combination of the [list](https://about.okkur.org/syna/fragments/list) and [content](https://about.okkur.org/syna/fragments/content) fragments
