### ISSUE TITLE
Disabling portfolio modal feature 

### ISSUE THREAD

**Issue by mherd12** [digitalcraftsman/hugo-agency-theme#125]
I'd like to disable the modal feature for the portfolio boxes so that it no longer opens into the extra window. Instead, I want to hyperlink the boxes to another website. How can I disable the modal so that it can be hyperlinked instead?

**Comment by stp-ip** [comment]
Hugo agency theme isn't adding new features at this time. There is a new Theme called `Syna`, based on it, which is more flexible see here: https://about.okkur.org/syna/fragments/portfolio/
