### ISSUE TITLE
Brand logo

### ISSUE THREAD

**Issue by tattooseoul** [digitalcraftsman/hugo-agency-theme#126]
I did manage to change the text logo but I'd like to replace it by an image. 
I added a "logo.svg" file into the img/ directory but it doesn't seem to be working.

**Comment by stp-ip** [comment]
You also have to set it within your config:
.Site.Params.navigation.logo needs to say "logo.svg" and it must be located within "img/", which you mentioned is already done.

Overall you might want to look into [Syna](https://syna.okkur.org) as it has more features and is still fully maintained.

**Comment by tattooseoul** [comment]
Thank you for your quick answer.
You mean set it within the config.toml file? 
Do I just add the following lines:

[Site.Params.navigation.logo]
logo = "logo.svg"

I'm also looking into Syna and managed to run the exampleSite on http://localhost:1313/.

**Comment by stp-ip** [comment]
The config file lines would be:

```
  [params.navigation]
    brand = "The Agency"
    # Optional logo as brand stored in img/
    logo = "logo.svg"
```

**Comment by stp-ip** [comment]
The easiest to get started with syna is https://syna.okkur.org/start with most documentation available here: https://syna.okkur.org/demo.
