### ISSUE TITLE
Only show non empty contact form fields

### ISSUE THREAD

**Issue by Shwelu** [digitalcraftsman/hugo-agency-theme#20]
Hi,

When I comment out the phone field in the contact fom as 

`# [params.contact.form.phone]
        # text = "Your Phone *"
        # warning = "Please enter your phone number."`

it still shows as in attachment.
Plz guide how to remove it completely.

Thanks in advance.
![shot_359](https://cloud.githubusercontent.com/assets/18285264/14281031/9784fdfe-fb04-11e5-935c-a4a5eb37d4ec.png)

**Comment by digitalcraftsman** [comment]
Hello @Shwelu,

first of all excuse my late response. `[params.contact.form.phone]` only changes the placeholder in the text field. There is no direct option to hide this field from the form.

Therefore, we have to modify the [corresponding template](https://github.com/digitalcraftsman/hugo-agency-theme/blob/master/layouts/partials/contact.html#L23-L26). Either delete the highlighted lines or comment them out.

**Comment by digitalcraftsman** [comment]
Is this still an issue?

**Comment by digitalcraftsman** [comment]
Closing this as stall.

**Comment by stp-ip** [comment]
Could be reopened with the title: "Only show non empty contact form fields".
That might be something I can work on next time I get the time.

**Comment by digitalcraftsman** [comment]
If I understand you correctly you would like to hide certain input fields of the form if no [`text`](https://github.com/digitalcraftsman/hugo-agency-theme/blob/master/exampleSite/config.toml#L234) attribute was set in the config file?

**Comment by stp-ip** [comment]
Right. The thought in addition was that this issue is related and might work better than opening another one ;)
