### ISSUE TITLE
Does description in the portfolio part support markdown?

### ISSUE THREAD

**Issue by datafibers** [digitalcraftsman/hugo-agency-theme#21]
Does description in the portfolio part support markdown syntax? For example, I want to type following format in the project description align left
- 2131
- 1313
- 1312

**Comment by digitalcraftsman** [comment]
Hello @datafibers,

the description in the portfolio modals [does support](https://github.com/digitalcraftsman/hugo-agency-theme/blob/master/layouts/partials/modals.html#L18) for basic formatting. 

The description is centered with by the CSS stylesheet of the project. Markdown would not have any influence on the alignment. You would need to change it yourself.

**Comment by datafibers** [comment]
I am trying
- 2131
- 1313
- 1312
  only the first line got proper bullet point. The other shows \* for instead.

**Comment by digitalcraftsman** [comment]
I tested it with the given YAML files for the project. The solution was to use the right behavior for the multi-line strings (`>` vs `|`):

``` yaml
description: |
  Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo! <br><br>**Want these icons in this portfolio item sample?** You can download 60 of them for free, courtesy of [RoundIcons.com](//getdpd.com/cart/hoplink/18076?referrer=bvbo4kax5k8ogc), or you can purchase the 1500 icon set [here](//getdpd.com/cart/hoplink/18076?referrer=bvbo4kax5k8ogc).

  * one
  * two
  * three
```

The above snippet worked fine for me. But I don't think that the final result is what you expected. The bullet points remain on the left but the text is centered.

**Comment by datafibers** [comment]
Thanks. It works. But, there has to have one space in front of the paragraph, such as "_" before "Use". Or else, it has errors to parse the file. Regarding text-align, I figure it out by modifying the CSS finally. If it is configurable, it will be cool. In addition, if the theme can integrate https://github.com/VincentGarreau/particles.js/, it will be cool. I try to add it to this them in the hero.html, but it is not perfect and not mobile browser friendly.
Anyway, close this issue since my problem is resolved.

**Comment by digitalcraftsman** [comment]
> Regarding text-align, I figure it out by modifying the CSS finally. If it is configurable, it will be cool.

The easiest way is to change the stylesheet. I included an option to easily [link CSS and JS files](https://github.com/digitalcraftsman/hugo-agency-theme/blob/master/CHANGELOG.md) from the config file. This way you don't have to touch the original stylesheet. Just overwrite in your custom css the properties that you want to change.

The integration of particle.js is a customization that is better left to you. Other users could request and integration of library XYZ and not all users will use them.

Best regards,
Digitialcraftsman
