### ISSUE TITLE
Quick question re: blog

### ISSUE THREAD

**Issue by luxpir** [digitalcraftsman/hugo-agency-theme#22]
Just checking that the best way to add a blog is to run another Hugo instance in a subdir/subdomain (thinking of using Detox theme for the moment) and add an external link?

If there's another way to add posts, I'm all ears.

Thanks for the theme, it's great.

**Comment by digitalcraftsman** [comment]
Hello @luxpir,

there was a similar question in the forum. Maybe the [approaches](https://discuss.gohugo.io/t/how-to-combine-two-hugo-themes/3244) described there work for you.

The config file allows you to [add custom links](https://github.com/digitalcraftsman/hugo-agency-theme/blob/master/exampleSite/config.toml#L50) easily.

**Comment by sandys** [comment]
hi,
I'm gonna echo what a lot of others have asked for - which is blog support. I also see the support for block templates in issue #41 .

I'm wondering how do you guys go about combining two different themes in hugo ? ultimately, I'm gonna be hosting on github pages. so I want one codebase that I can generate html files from and upload to github pages.
abc.github.io -> main site (agency theme)
abc.github.io/blog -> blog site 

how do I do this - does anyone have an example ?

**Comment by stp-ip** [comment]
As hugo-agency-theme is mostly in maintenance mode and no new features will be added.
We created [Syna](https://syna.okkur.org) as a more flexible iteration of this theme.

Syna can create a native blog integration (currently without an rss feed for now) with the combination of the [list](https://about.okkur.org/syna/fragments/list) and [content](https://about.okkur.org/syna/fragments/content) fragments
