### ISSUE TITLE
Template is missing: _internal/google_analytics.html

### ISSUE THREAD

**Issue by calendarbase** [digitalcraftsman/hugo-agency-theme#24]
This is referenced in layout  partials in the js.html file:
{{ template "_internal/google_analytics.html" . }}

But there is no such file.

I can, of course, whip one up myself, but how should it look like?

**Comment by digitalcraftsman** [comment]
Hello @calendarbase,

template is shipped with Hugo itself. It was introduced with Hugo v0.15. Therefore, I assume you're using an older version. I would suggest an update to either v0.15 or the latest release v0.16.

**Comment by calendarbase** [comment]
Ok, got it!
Now I have an issue with the async version, which can not be found in Hugo v0.15: {{ template "_internal/google_analytics_async.html" . }}

But i just read that it is only in v0.16 if I understand it right. Not sure if there is no memory leaks in the newest version so I will use v0.15.

Closing this issue now!

**Comment by digitalcraftsman** [comment]
According to the release notes the async template was introduced with v0.16. You can find the template [here](https://github.com/spf13/hugo/blob/2c5e4f7640e71d2a193a74e6c41109ec40bc0222/tpl/template_embedded.go#L238-L245) if you want to create your own template. This would allow you to use it with v0.15 too.
