### ISSUE TITLE
safehtml not defined

### ISSUE THREAD

**Issue by ajayep** [digitalcraftsman/hugo-agency-theme#3]
When I use the template with hugo binary 0.13 I get the below errors

hugo server
ERROR: 2015/06/23 template: theme/partials/about.html:1: function "safeHTML" not defined
ERROR: 2015/06/23 template: theme/partials/clients.html:1: function "safeHTML" not defined
ERROR: 2015/06/23 template: theme/partials/contact.html:1: function "safeHTML" not defined
ERROR: 2015/06/23 template: theme/partials/footer.html:1: function "safeHTML" not defined
ERROR: 2015/06/23 template: theme/partials/head.html:8: function "safeHTML" not defined
ERROR: 2015/06/23 template: theme/partials/hero.html:1: function "safeHTML" not defined
ERROR: 2015/06/23 template: theme/partials/js.html:1: function "safeHTML" not defined
ERROR: 2015/06/23 template: theme/partials/modals.html:1: function "safeHTML" not defined
ERROR: 2015/06/23 template: theme/partials/nav.html:1: function "safeHTML" not defined
ERROR: 2015/06/23 template: theme/partials/portfolio.html:1: function "safeHTML" not defined
ERROR: 2015/06/23 template: theme/partials/services.html:1: function "safeHTML" not defined
ERROR: 2015/06/23 template: theme/partials/team.html:1: function "safeHTML" not defined
ERROR: 2015/06/23 html/template: "theme/partials/head.html" is an incomplete template in theme/partials/head.html
ERROR: 2015/06/23 html/template: "theme/partials/nav.html" is an incomplete template in theme/partials/nav.html
ERROR: 2015/06/23 html/template: "theme/partials/hero.html" is an incomplete template in theme/partials/hero.html
ERROR: 2015/06/23 html/template: "theme/partials/services.html" is an incomplete template in theme/partials/services.html
ERROR: 2015/06/23 html/template: "theme/partials/portfolio.html" is an incomplete template in theme/partials/portfolio.html
ERROR: 2015/06/23 html/template: "theme/partials/about.html" is an incomplete template in theme/partials/about.html
ERROR: 2015/06/23 html/template: "theme/partials/team.html" is an incomplete template in theme/partials/team.html
ERROR: 2015/06/23 html/template: "theme/partials/clients.html" is an incomplete template in theme/partials/clients.html
ERROR: 2015/06/23 html/template: "theme/partials/contact.html" is an incomplete template in theme/partials/contact.html
ERROR: 2015/06/23 html/template: "theme/partials/footer.html" is an incomplete template in theme/partials/footer.html
ERROR: 2015/06/23 html/template: "theme/partials/modals.html" is an incomplete template in theme/partials/modals.html
ERROR: 2015/06/23 html/template: "theme/partials/js.html" is an incomplete template in theme/partials/js.html
0 of 1 draft rendered 
0 future content 
0 pages created 
0 paginator pages created 
0 tags created
0 categories created
in 16 ms
Serving pages from /Users/ajay/hugo/site1/public
Web Server is available at http://localhost:1313/
Press Ctrl+C to stop

**Comment by digitalcraftsman** [comment]
@ajayep I'm currently using (and developed) this theme with Hugo v0.14. For testing purposes I tried to recreate the errors by cloning the theme into a fresh environment a few moments ago. With Hugo v0.14 worked everything perfectly. 

`safeHTML`, which seems to cause the problems on your system, is the template function that I'm using to escape HTML comments. The [release notes of Hugo v0.14](https://github.com/spf13/hugo/releases) mention under `Notice` that `safeHtml` is renamed to `safeHTML`. But the release notes also say:

> These will still work in 0.14, but will be removed in 0.15.

Maybe you should consider to update to the latest release and see if the problems still occurs.

**Comment by ajayep** [comment]
@digitalcraftsman  I confirm it was issue with building with v0.13 . With v0.14 it works out of the box. Thanks a lot for creating such a wonderful Hugo theme.

**Comment by digitalcraftsman** [comment]
I'm glad that everything works fine now.
