### ISSUE TITLE
Add option to disable or exchange contacts provider

### ISSUE THREAD

**Issue by stp-ip** [digitalcraftsman/hugo-agency-theme#35]
Not sure on the implementation yet, but wanted to log the issue upstream already.

**Comment by digitalcraftsman** [comment]
With contact provider you mean Formspree as service to handle the contact form, right?

It would be nice to make this more customizable. But each contact provider uses a (slightly) different approach. Combining them all in one template (if possible) would create unreadable code. Alternatively, using different templates would make the code redundant.

My suggestion is that you copy the contact partial to `layouts/partials/` in the root directory. You can adapt this template with your own provider. Furthermore, you can update the theme without worrying that your changes will be removed. Templates in the root directory will overwrite those of the theme.

I think this is the most flexible solution for all of us.

**Comment by stp-ip** [comment]
Yeah that sounds almost better than my initial ideas. The initial idea was to make default formspree and $provider just using a POST url, but the partials idea seems probably cleaner.
Will check back, when I have some code.
