### ISSUE TITLE
Add multi-language support

### ISSUE THREAD

**Issue by jlcs-es** [digitalcraftsman/hugo-agency-theme#49]
I customize some months ago your awesome template to fix some of the things that the last 50 mails have notified me, and to add multi-language support.

In 2-3 months I will have enough spare time to adapt my code to the new commits and clean it up to make a pull-request, if you don't mind.

I open the issue so if in this 2-3 months anybody wants to do it, 2 months earlier for everybody to have the feature.

**Comment by digitalcraftsman** [comment]
Hello @jlcs-es,

as you can read in #41 there are plans to exend this template from a single page layout to a more flexible theme that might support sub-pages like a blog etc. Supporting multilingual pages is definitely an aspect that we should take into account.

I'm not sure when this enhancements will be added. It could be possible that the codebase will diverge from yours in the next couple of months. Contributions are always welcome.

**Comment by stp-ip** [comment]
As hugo-agency-theme is mostly in maintenance mode and no new features will be added.
We created [Syna](https://syna.okkur.org) as a more flexible iteration of this theme.

Syna is working on multi language support tracked in issue https://github.com/okkur/syna/issues/14.
