### ISSUE TITLE
Used contact form validation library does not support new TLDs

### ISSUE THREAD

**Issue by stp-ip** [digitalcraftsman/hugo-agency-theme#54]
Switch to another validation library. Maybe after moving to the latest bootstrap version.

Relevant issue:
https://github.com/ReactiveRaven/jqBootstrapValidation/issues/185

**Comment by stp-ip** [comment]
For now the library is hot patched. To make this clear the library is marked as -dirty in its version.
Probably best to leave it open as switching to a newer library might still be worth it.

**Comment by digitalcraftsman** [comment]
> Probably best to leave it open as switching to a newer library might still be worth it.

I agree. jqBootstrapValidation doesn't seem to be actively maintained.

**Comment by stp-ip** [comment]
Suggestion is https://jqueryvalidation.org/.
Will see, if I can migrate in the coming days.
