### ISSUE TITLE
Move content into separate files

### ISSUE THREAD

**Issue by stp-ip** [digitalcraftsman/hugo-agency-theme#62]
The first idea is to have the following content structure:

**content/page/$single_pages.md**
**content/elements/service/$serviceA.md**
**content/elements/contact.md**

Services and other elements could be sorted by weight first and by date second.
Each element or item within a frontpage element has its own file. Global settings like disabling elements would still live in config.toml, but usual default would be, if a file is available for an element it is considered enabled and needs to optionally be disabled in config.toml.

Furthermore the email and contact form provider could be considered global settings and be kept in config.toml.

As this will break compatibility a major version change should occur.

**Comment by digitalcraftsman** [comment]
Wouldn't it be easier to move the services, events in the about section as well as the team member descriptions in data files? This way we can sort them by date and weight too. And it trivial to check if a data file for a certain category is present or not.

> Furthermore the email and contact form provider could be considered global settings and be kept in config.toml.

I agree.

To flatten the config file even more we could move the definition of strings as well by using the i18n feature of Hugo. Simultaneously we could start to add full support for i18n.

> As this will break compatibility a major version change should occur.

I should start to tag future versions of this theme.

**Comment by stp-ip** [comment]
I would define content for the services etc. more as content than as data. Therefore I would use content files. Especially as single pages are also located there.

i18n support could first be done via these new separate files and within a second iteration all remaining strings should be extracted into a config or content within these files. So first separate and then move the remaining strings.
At least that's how I understood i18n support. It's basically just another content file with a postfix such as _en.md or _de_DE.md for example. So all strings (config and content) defined in there are already translatable. 

Probably the last feature on the non breaking branch would be single page. Afterwards I would prefer a breaking change as compatibility will become hard. Should we just use the dev branch then?

**Comment by digitalcraftsman** [comment]
> Afterwards I would prefer a breaking change as compatibility will become hard. Should we just use the dev branch then?

Yes. `master` should only contain backwardscompatible (for now) and stable commits.

**Comment by stp-ip** [comment]
So with hugo 0.18 nodes will be gone and all elements will be pages. I am still looking through the code to find out how to make the changes we want work with hugo 0.18.

So basically we have a good breaking point.

**Comment by stp-ip** [comment]
Seems like its coming along nicely. Quite a huge rewrite. So it might take me a bit to finish this up (not the main focus unfortunately).

Currently all elements on the front page are located within a special section "index".
Each element is its own file and handles their config within the front matter.
For some elements data files are used. As example: team, services, about/timeline.

I still have to add sorting and finish the migration to this new structure.

Maybe a first iteration is working in the coming week.

**Comment by digitalcraftsman** [comment]
Regarding Hugo v0.18: a new release in the near future is not planned. Hence I think we could use v0.17 as breakpoint instead. We could already make use of block templates and the i18n feature if you like.

> I still have to add sorting and finish the migration to this new structure.
> Maybe a first iteration is working in the coming week.

Your ideas for the revisions are good.

**Comment by stp-ip** [comment]
It seems currently I am still using only 0.17 features. I am still looking into the actual differences of the specific change and asked the dev to jump in.

Still have a small unresolved issue with the timeline and modBool.

Wanted to do something like:
```
{{ range sort $i, $e := $.Site.Data.timeline }}
  <li {{ if (not (modBool $i 2)) }}class="timeline-inverted" {{ end }}>
```

But the index doesn't work there as one would image due to $i not being an integer, but a string.
The content of $.Site.Data.timeline is something like:
```map[beginnings:map[description:Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur! title:Our Humble Beginnings weight:10 img:1.jpg date:2009-2011]]```

How would one get the index of one specific event?

**Comment by digitalcraftsman** [comment]
The latest version of Hugo was a template function called [`int`](https://gohugo.io/templates/functions/#int) that allows you to cast `$i` to an integer.

**Comment by stp-ip** [comment]
Still wouldn't work as $i would be "beginnings" in this case. I am looking into a counter within the range loop. But couldn't yet figure out how this can be done without making it complex.

**Comment by stp-ip** [comment]
Got it working:

```
{{ $.Scratch.Set "counter" 0 }}
{{ range sort $.Site.Data.timeline }}
  {{ $i := $.Scratch.Get "counter" }}
  <li {{ if (not (modBool $i 2)) }}class="timeline-inverted" {{ end }}>
  {{ $.Scratch.Add "counter" 1 }}
{{ end }}
```

**Comment by stp-ip** [comment]
As hugo-agency-theme is mostly in maintenance mode and no new features will be added.
We created [Syna](https://syna.okkur.org) as a more flexible iteration of this theme.

Syna is uses separate content files to create a website. Each fragment making up a single site is also split into multiple files within the same directory. For more information take a look at the [documentation](https://syna.okkur.org/docs/).
