### ISSUE TITLE
Add language switcher

### ISSUE THREAD

**Issue by digitalcraftsman** [digitalcraftsman/hugo-agency-theme#67]
Have a look at the `dev` branch which adds support for i18n.

**Comment by louisiscoding** [comment]
Would be super useful to have one ! :+1:

**Comment by stp-ip** [comment]
As hugo-agency-theme is mostly in maintenance mode and no new features will be added.
We created [Syna](https://syna.okkur.org) as a more flexible iteration of this theme.

Syna is working on multi language support tracked in issue https://github.com/okkur/syna/issues/14.
