### ISSUE TITLE
Two validations errors

### ISSUE THREAD

**Issue by bengudro** [digitalcraftsman/hugo-agency-theme#7]
Hello DigitalCraftsman.  I’m trying to use your _exellent_ theme.  It works fine except when I run it through the _very useful_ [html5 validator](https://html5.validator.nu/), it throws two erros:
1. `Line 15` in your [head partial](https://github.com/digitalcraftsman/hugo-agency-theme/blob/master/layouts/partials/head.html) should really be on two lines, with your quotation marks fixed, so that:
   
   `<link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet" type="text/css'>" link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css">`
   
   becomes:
   
   `<link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet" type="text/css">`
   
   `<link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css">`
2. Between `line 24` and `line 25` in you [team partial](https://github.com/digitalcraftsman/hugo-agency-theme/blob/master/layouts/partials/team.html):
   
   you should insert a `</div>` in there (you omitted to close your `<div class="row">` that was openned on `line 10`
3. Also in that [same file](https://github.com/digitalcraftsman/hugo-agency-theme/blob/master/layouts/partials/team.html) at `line 19` you omitted to close the `<li>` so that:
   
   `<li><a href="{{ index . 1 }}"><i class="fa {{ index . 0 }}"></i></a>`
   
   should become:
   
   `<li><a href="{{ index . 1 }}"><i class="fa {{ index . 0 }}"></i></a></li>`
   
   (**Note:** the [html5 validator](https://html5.validator.nu/) did not complain about that last one, it’s just something I noticed.)

That’s it, thanks!

**Comment by digitalcraftsman** [comment]
Thanks for creating that detailed issue. And it's nice to see the theme in the wild.
