### ISSUE TITLE
Custom SVG for param.services.row.list

### ISSUE THREAD

**Issue by louisiscoding** [digitalcraftsman/hugo-agency-theme#70]
Hi,

I'd like to use a SVG file which is not available from fontawesome.io ( The Angular Library icon).
Is there a recommended guideline i could follow to use it ?

Thanks x. :+1:

**Comment by stp-ip** [comment]
Will try to look into it within the coming dev branch. Will take a bit so.

**Comment by stp-ip** [comment]
You can add your custom font-awesome font. One can be created with your own icons here: https://icomoon.io/app/#/select

I'll see if that might be made easier, but this should make everything possible for you.
