### ISSUE TITLE
Successfully submittied form causes an error message

### ISSUE THREAD

**Issue by freddix** [digitalcraftsman/hugo-agency-theme#71]
For some reason successfully submitted message always returns an error message. This was previously not the case, the formspree thanks page was shown instead. I guess, it has something with the migration to jquery.form-validator, but I am not sure how to nail it down.
Using standard configuration, no modifications made to any involved files.

**Comment by stp-ip** [comment]
Will try to look into it within the coming dev branch. Will take a bit so.

**Comment by stp-ip** [comment]
If this is still a bug, let us know. Closing for now.
