### ISSUE TITLE
Best way to add disclaimer / impress

### ISSUE THREAD

**Issue by anoehre** [digitalcraftsman/hugo-agency-theme#72]
What is the best way to add an extra page for additional content like a disclaimer or an impress?

**Comment by stp-ip** [comment]
Will be available within the dev branch. You then just use prost/prepend in the menu and add your content file.
When I finish the dev changes and update some documentation, I'll update the issue here.

Might take a bit as I have a huge backlog from being on vacation.

**Comment by anoehre** [comment]
Yeah! Great to hear. Thanks for your support and the good work.

**Comment by unclesamwk** [comment]
Hello,

is this feature also live?

greetings
sam

**Comment by stp-ip** [comment]
It's only available via the dev branch right now. Hope I can continue work on it with the latest features coming out of Hugo. It's just not that easy to have multiple files produce a single page website.

For more information see https://discuss.gohugo.io/t/single-page-with-nested-content/2645 and https://discuss.gohugo.io/t/homepage-content-from-content-home-md/54/21

**Comment by unclesamwk** [comment]
Where can i send paypal donation :-) ???
Please finish this work.

**Comment by stp-ip** [comment]
@unclesamwk Next time I have to work on it is mid June. That's when I want to push it into a production state. No clear completion ETA, but I haven't forgotten.

Thanks for proposing a donation, but let's first finish the work.

**Comment by rwieruch** [comment]
Hello there. Thank you for this awesome theme! Is there any update regarding the possibility to add another page? I want to use 

    [[params.footer.quicklinks]]
      text = "Impress"
      link = "/impress"

But when I add a impress.md in content/ it doesn't show up. Thanks for your help!

**Comment by stp-ip** [comment]
We decided to do the major rework changes within a new theme: github.com/okkur/syna, to reduce breaking changes within this theme. A few things might be backported, but no ETA for that.

Syna is currently going through a last big change from data files to page bundles, but after that it should be quite stable.

**Comment by rwieruch** [comment]
Ah okay. You are doing great work there! Any chance that you know how to get a separate page running with the agency theme? Unfortunately I thought creating a file such as content/impress.md should be sufficient, but it wasn't. Otherwise I could just link to an external Impress site.

**Comment by stp-ip** [comment]
You can manually patch the agency theme. Add the _default folder + contents from the dev branch to layouts within your site (that helps to overwrite the main theme): https://github.com/digitalcraftsman/hugo-agency-theme/tree/dev/layouts/_default.
This should enable single pages as you did.

**Comment by rwieruch** [comment]
Thanks it worked! I had to copy the `layouts/partials/single.html` too.

**Comment by stp-ip** [comment]
Yeah forgot to mention that. We already split up the single page into a partial in our WIP dev branch.
Will see what makes sense in terms of bringing back some solutions to agency from syna. Unfortunately time is always limited. Great that it worked.

**Comment by stp-ip** [comment]
As hugo-agency-theme is mostly in maintenance mode and no new features will be added.
We created [Syna](https://syna.okkur.org) as a more flexible iteration of this theme.

Syna does support adding a [content fragment](https://about.okkur.org/syna/fragments/content) to implement this.
