### ISSUE TITLE
include CC license in footer

### ISSUE THREAD

**Issue by maxheld83** [digitalcraftsman/hugo-agency-theme#73]
it would be nice to have a properly formatted CC license in the footer, perhaps in the style of the social links.
CC provides nice html for this purpose, like so, from: https://creativecommons.org/choose/

```
<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons Lizenzvertrag" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a><br />Dieses Werk ist lizenziert unter einer <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Namensnennung - Nicht kommerziell - Keine Bearbeitungen 4.0 International Lizenz</a>
```

**Comment by stp-ip** [comment]
Will take the idea into account for the dev branch. No ETA or promise to implement yet.

**Comment by stp-ip** [comment]
As hugo-agency-theme is mostly in maintenance mode and no new features will be added.
We created [Syna](https://syna.okkur.org) as a more flexible iteration of this theme.

Syna does support customizing a [footer fragment](https://about.okkur.org/syna/fragments/copyright) to implement this.
