### ISSUE TITLE
add powered by Hugo, digitalcraftsman in footer

### ISSUE THREAD

**Issue by maxheld83** [digitalcraftsman/hugo-agency-theme#74]
I'd like to give a shoutout to Hugo and @digitalcraftsman and the upstream creators in my usage of the theme. Could you add something like that to the footer properly designed? I'd love that.
Thanks for the great work.

**Comment by stp-ip** [comment]
As hugo-agency-theme is mostly in maintenance mode and no new features will be added.
We created [Syna](https://syna.okkur.org) as a more flexible iteration of this theme.

Syna does support adding a customized [footer fragment](https://about.okkur.org/syna/fragments/copyright) to implement this.
