### ISSUE TITLE
fix oddly asymmetric layout of team

### ISSUE THREAD

**Issue by maxheld83** [digitalcraftsman/hugo-agency-theme#75]
this looks weird to me because it is not centered. Feels like there should be 3 per row perhaps?

![assymetric](https://cloud.githubusercontent.com/assets/5372770/21998494/797dd11a-dc35-11e6-8298-88552d50b193.png)

oddly, upstream at https://blackrockdigital.github.io/startbootstrap-agency/ the layout IS symmetric with 3 per row:

![symmetric](https://cloud.githubusercontent.com/assets/5372770/21998526/a2194564-dc35-11e6-85b4-440c66ad0590.png)

**Comment by stp-ip** [comment]
Which branch are you using?
What browser?
This should have been fixed in the dev branch.
The latest changes enabled centering of the team and the default with having 3 symmetric team members per line.

**Comment by maxheld83** [comment]
Sorry, this is Safari, and I am using the master branch.
But you mentioned that the dev branch isn't quite ready for prime time yet, correct?

**Comment by stp-ip** [comment]
Let's say it works and is in production with a subset of the features, but without documentation I would not recommend using it yet.
Will try to look into the issue in the next days and add a backport, if necessary.

**Comment by ekeih** [comment]
Hi,
are there any news about this issue?
The left-alignment looks really strange if you have only one or two team members. So it would be great to have it centered.

Anyway, thanks for the great theme!

Best regards
Max

EDIT:
I added

```
#team > div > div.row.flexbox > div {
  margin: auto;
}
```

to my CSS code to center a single "team" member.

**Comment by stp-ip** [comment]
As hugo-agency-theme is mostly in maintenance mode and no new features will be added.
We created [Syna](https://syna.okkur.org) as a more flexible iteration of this theme.

This should be fixed in Syna and it's corresponding [member fragment](https://about.okkur.org/syna/fragments/member)
