### ISSUE TITLE
add testimonials to main page

### ISSUE THREAD

**Issue by maxheld83** [digitalcraftsman/hugo-agency-theme#76]
I know this isn't part of the original, upstream agency theme, but I thought I'd add this here anyway as a suggestion.

**Comment by stp-ip** [comment]
Good suggestion. Not sure, if I will implement it soon, but maybe after the new dev branch is finished someone might add it easily.

**Comment by stp-ip** [comment]
As hugo-agency-theme is mostly in maintenance mode and no new features will be added.
We created [Syna](https://syna.okkur.org) as a more flexible iteration of this theme.

If you feel Syna could need this feature let us know and create an [issue](https://github.com/okkur/syna/issues/new).
