### ISSUE TITLE
add image credit for background images

### ISSUE THREAD

**Issue by maxheld83** [digitalcraftsman/hugo-agency-theme#78]
It would be really nice if the backround images could support an image credit and url field, sometimes important for licensing stuff etc.

The Jekyll template [Minimal Mistakes](https://mmistakes.github.io/minimal-mistakes/docs/layouts/) as implemented this quite nicely via YAML front matter.

**Comment by stp-ip** [comment]
As hugo-agency-theme is mostly in maintenance mode and no new features will be added.
We created [Syna](https://syna.okkur.org) as a more flexible iteration of this theme.

If you feel Syna could need this feature let us know and create an [issue](https://github.com/okkur/syna/issues/new).
