### ISSUE TITLE
contact form fails when recaptcha challenge is returned

### ISSUE THREAD

**Issue by jpalczewski** [digitalcraftsman/hugo-agency-theme#79]
Hi, 

I successfully configured theme(It's great, thanks!), but encountered problem - when formspree thinks that I'm a bad guy, sends me back an recaptcha on their site - but site doesn't notice about it(even warning message isn't displayed), so it's seems unresponsible.

Hotfix? It works better when appropriate function from agency.js is removed, but maybe some response-dependent logic is necessary if async form is priority.

#61

**Comment by stp-ip** [comment]
Will remove the async functionality, when using formspree. Will leave it open until dev is stable.

**Comment by stp-ip** [comment]
As hugo-agency-theme is mostly in maintenance mode and no new features will be added.
We created [Syna](https://syna.okkur.org) as a more flexible iteration of this theme.

This should be fixed in Syna and it's corresponding [contact fragment](https://about.okkur.org/syna/fragments/contact)
