### ISSUE TITLE
Contact form submission button not displaying any message

### ISSUE THREAD

**Issue by soaprofessional** [digitalcraftsman/hugo-agency-theme#83]
When I am clicking on "Send Message" button of contact form, it is not showing any error or thank you message but I am able to receive the message in my email. I tried it in multiple browsers but the behaviors is same.

**Comment by jsevo** [comment]
Not sure this is the same issue, but I can see that I get a status 200 when pressing the button. Yet, no email arrives for me. I seem to not be forwarded to confirm that 'I am not a robot' which formspree would like to have me confirm. When I host a simple static website with the same formspree form this works and I receive the email.

**Comment by unclesamwk** [comment]
I've the same Problem too ... Status 200, Confirmation email i recieved but no future emails were send and no message displays

**Comment by soaprofessional** [comment]
I changed my settings to use http://enformed.io/ and started receiving the messages in email.For the confirmation message to appear, I had to update the "// Async contact form" section in agency.js file to process the  response as a string : if (res.indexOf("success"))      $('form[id=contactForm] #success').show();    else     $('form[id=contactForm] #error').show();

 Regards,
Mohammed

http://www.techdriven.me 

    On Monday, April 17, 2017 2:00 AM, jsevo <notifications@github.com> wrote:
 

 Not sure this is the same issue, but I can see that I get a status 200 when pressing the button. Yet, no email arrives for me. I seem to now be forwarded to confirm that 'I am not a robot' which formspree would like to have me confirm. When I host a simple static website with the same formspree form this works and I receive the email.—

**Comment by hangyao** [comment]
Hi @soaprofessional !
I used your method, the emails can be sent through http://enformed.io to my email address, however, neither the success nor error message will show up once clicking the submit button. Any advice on that? Thank you!

Here is the code:
```javascript
// Async contact form
$('form[id=contactForm]').submit(function(){
  $.post($(this).attr('action'), $(this).serialize(), function(res){
    $('form[id=contactForm] #success').hide();
    $('form[id=contactForm] #error').hide();
    if (res.indexOf("success"))
      $('form[id=contactForm] #success').show();
    else $('form[id=contactForm] #error').show();
  }).fail(function(){
    $('form[id=contactForm] #success').hide();
    $('form[id=contactForm] #error').hide();
    $('form[id=contactForm] #error').show();
  });
  return false;
});
```

**Comment by analytical** [comment]
It worked for me. I'm using formspree.io
