### ISSUE TITLE
contact form not working

### ISSUE THREAD

**Issue by liz-miller** [digitalcraftsman/hugo-agency-theme#84]
I can't seem to get the contact form to work on my site (lizmillerfit.com). I received 1 confirmation email (and confirmed it), but I cannot submit any messages via this form. Does anyone have a solution to this? Thanks

**Comment by acolominas** [comment]
I have the same problem!

**Comment by acolominas** [comment]
I fix it!
I follow the instructions explained in #83 

> I changed my settings to use http://enformed.io/ and started receiving the messages in email.For the confirmation message to appear, I had to update the "// Async contact form" section in agency.js file to process the  response as a string : if (res.indexOf("success"))      $('form[id=contactForm] #success').show();    else     $('form[id=contactForm] #error').show();
 Regards,
Mohammed

You must create an account at enformed.io and use enformed.io instead of formspree.io

Arnau

**Comment by stp-ip** [comment]
Enformed is a nice alternative. There is also a selfhosted alternative with [mailout](https://github.com/SchumacherFM/mailout) and [caddy](https://caddyserver.com).

Formspring seems to have been unable to send mails for about a week, but they seem to have resolved that issue. Will close it for now.
