### ISSUE TITLE
Height of background image

### ISSUE THREAD

**Issue by Paul-Reed** [digitalcraftsman/hugo-agency-theme#89]
The theme looks great on a laptop/desktop - thank you!
On a mobile display, the hero background however does not extend to the height of the screen, and it looks a little strange.
Is there a way to increase the height of the image please?

![agency](https://user-images.githubusercontent.com/973580/29244276-fe7d9d68-7fab-11e7-91c5-45d079a5397f.png)

**Comment by stp-ip** [comment]
Yes you can. Duplicate the agency.css to your own files so it overwrites the theme default and then you can add "height: 800px;" in the "header { }" section. As it completely depends on the phone size how big it needs to be. I'll close this for now. We could do some resizing with the device size, but that is out of scope for now. Will add a note to maybe revisit this in the future.

**Comment by jwkvam** [comment]
I added `height` to the header in css in agency.css
```
header {
    text-align: center;
    color: #fff;
    height: 100vh;
```

**Comment by Paul-Reed** [comment]
That's great, thanks.
