### ISSUE TITLE
Easy way to change colors?

### ISSUE THREAD

**Issue by jwkvam** [digitalcraftsman/hugo-agency-theme#90]
I'm not a web developer so bear with me. Is there an easy way to change the color scheme? I see there's a bunch of css in agency.css that references the yellow color (#fed136) for instance. I would like to replace it. Is there a better way than just search and replacing them? Thanks!

**Comment by stp-ip** [comment]
Not really. We could use the latest outputFormats from hugo, but this would bloat the configuration and the theme. Easier to just copy the agency.css to your own directory (same path) so it overwrites the theme one and then search and replace.
