### ISSUE TITLE
How can I change the background color?

### ISSUE THREAD

**Issue by ozbillwang** [digitalcraftsman/hugo-agency-theme#99]
In the `exampleSite`, The background color  `tell me more`, and others are yellow. 

Any easy way to change the background color to others? I mean how to customize own css file?

     custom_css = ["css/own.css"]

Same questions for how to change all texts' color from white to others.

**Comment by ozbillwang** [comment]
The related css file is `static/css/agency.css`. But how to write own css to change the color? tried, but no different. Any hints for me?

**Comment by stp-ip** [comment]
Either you overwrite the agency.css or provide your own options within a custom_css. These have to overwrite all colours. Sometimes various shades are used and you need to overwrite all of them. Usually the easiest is to copy the agency.css, remove all non color related stuff, remove all colors you don't wanna change and then swap out the colors you want to change and use that as your custom_css.

Hope that helps.
